# Generated by Django 4.0.5 on 2022-06-17 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stone',
            name='image',
            field=models.CharField(default='0000-00-00', max_length=3000),
        ),
    ]
